[2025-02-01T02:06:06.320+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_to_bigquery_dag.upload_to_bigquery manual__2025-02-01T02:05:57.794440+00:00 [queued]>
[2025-02-01T02:06:06.325+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_to_bigquery_dag.upload_to_bigquery manual__2025-02-01T02:05:57.794440+00:00 [queued]>
[2025-02-01T02:06:06.325+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-02-01T02:06:06.332+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_bigquery> on 2025-02-01 02:05:57.794440+00:00
[2025-02-01T02:06:06.335+0000] {standard_task_runner.py:57} INFO - Started process 1557 to run task
[2025-02-01T02:06:06.337+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gcs_to_bigquery_dag', 'upload_to_bigquery', 'manual__2025-02-01T02:05:57.794440+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/json_to_bigquery.py', '--cfg-path', '/tmp/tmp6_lqih5q']
[2025-02-01T02:06:06.339+0000] {standard_task_runner.py:85} INFO - Job 119: Subtask upload_to_bigquery
[2025-02-01T02:06:06.367+0000] {task_command.py:410} INFO - Running <TaskInstance: gcs_to_bigquery_dag.upload_to_bigquery manual__2025-02-01T02:05:57.794440+00:00 [running]> on host 3f33197bb456
[2025-02-01T02:06:06.441+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_to_bigquery_dag' AIRFLOW_CTX_TASK_ID='upload_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T02:05:57.794440+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T02:05:57.794440+00:00'
[2025-02-01T02:06:06.449+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-02-01T02:06:06.458+0000] {logging_mixin.py:150} INFO - üü¢ BigQueryÏóê ÏóÖÎ°úÎìúÌï† Îç∞Ïù¥ÌÑ∞: [{'date': '20250201', 'airline': '', 'flight_number': '', 'departure_airport': '', 'arrival_airport': '', 'departure_time': '', 'arrival_time': '', 'carbon_emission': 0.0}]
[2025-02-01T02:06:06.459+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/json_to_bigquery.py", line 134, in upload_to_bigquery
    "arrival_airport", "departure_time", "arrival_time", "carbon_emission"]
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 236, in insert_rows
    raise NotImplementedError()
NotImplementedError
[2025-02-01T02:06:06.465+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_to_bigquery_dag, task_id=upload_to_bigquery, execution_date=20250201T020557, start_date=20250201T020606, end_date=20250201T020606
[2025-02-01T02:06:06.474+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 119 for task upload_to_bigquery (; 1557)
[2025-02-01T02:06:06.479+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-02-01T02:06:06.503+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
