[2025-02-01T02:12:37.778+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_to_bigquery_dag.upload_to_bigquery manual__2025-02-01T02:07:31.126955+00:00 [queued]>
[2025-02-01T02:12:37.785+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_to_bigquery_dag.upload_to_bigquery manual__2025-02-01T02:07:31.126955+00:00 [queued]>
[2025-02-01T02:12:37.785+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2025-02-01T02:12:37.800+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_bigquery> on 2025-02-01 02:07:31.126955+00:00
[2025-02-01T02:12:37.804+0000] {standard_task_runner.py:57} INFO - Started process 1823 to run task
[2025-02-01T02:12:37.807+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gcs_to_bigquery_dag', 'upload_to_bigquery', 'manual__2025-02-01T02:07:31.126955+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/json_to_bigquery.py', '--cfg-path', '/tmp/tmpwzbs1z3r']
[2025-02-01T02:12:37.809+0000] {standard_task_runner.py:85} INFO - Job 125: Subtask upload_to_bigquery
[2025-02-01T02:12:37.843+0000] {task_command.py:410} INFO - Running <TaskInstance: gcs_to_bigquery_dag.upload_to_bigquery manual__2025-02-01T02:07:31.126955+00:00 [running]> on host 3f33197bb456
[2025-02-01T02:12:37.910+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_to_bigquery_dag' AIRFLOW_CTX_TASK_ID='upload_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T02:07:31.126955+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T02:07:31.126955+00:00'
[2025-02-01T02:12:37.917+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-02-01T02:12:37.927+0000] {logging_mixin.py:150} INFO - üü¢ BigQueryÏóê ÏóÖÎ°úÎìúÌï† Îç∞Ïù¥ÌÑ∞: [{'date': '20250201', 'airline': '', 'flight_number': '', 'departure_airport': '', 'arrival_airport': '', 'departure_time': '', 'arrival_time': '', 'carbon_emission': 0.0}]
[2025-02-01T02:12:38.613+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/json_to_bigquery.py", line 139, in upload_to_bigquery
    json_rows=transformed_data  # ‚úÖ JSON ÌòïÌÉú Í∑∏ÎåÄÎ°ú Ï†ÑÎã¨
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 3700, in insert_rows_json
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 816, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 354, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 POST https://bigquery.googleapis.com/bigquery/v2/projects/ticketchecker-449405/datasets/ticket_checker/tables/flight_lowest_prices/insertAll?prettyPrint=false: Not found: table Table is deleted: 219266565304:ticket_checker.flight_lowest_prices
[2025-02-01T02:12:38.630+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=gcs_to_bigquery_dag, task_id=upload_to_bigquery, execution_date=20250201T020731, start_date=20250201T021237, end_date=20250201T021238
[2025-02-01T02:12:38.644+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 125 for task upload_to_bigquery (404 POST https://bigquery.googleapis.com/bigquery/v2/projects/ticketchecker-449405/datasets/ticket_checker/tables/flight_lowest_prices/insertAll?prettyPrint=false: Not found: table Table is deleted: 219266565304:ticket_checker.flight_lowest_prices; 1823)
[2025-02-01T02:12:38.669+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-02-01T02:12:38.688+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
